#!/bin/bash

MONITORED_DIR="$(dirname "$2")"
[ "$SNAP_ARCH" == "amd64" ] && \
    MONITORED_DIR="${MONITORED_DIR/"Program Files"/"Program Files (x86)"}"

KILL_FILE="$SNAP_USER_COMMON/.kill-monitor"

touch "$KILL_FILE"
killall inotifywait
sleep 1
rm -f "$KILL_FILE"

function start_monitor() {
    while [ ! -f "$KILL_FILE" ]; do
        [ ! -d "$MONITORED_DIR" ] && continue
        chmod 755 "$MONITORED_DIR"
        inotifywait "$MONITORED_DIR"
    done
    [ -d "$MONITORED_DIR" ] && chmod 755 "$MONITORED_DIR"
}

start_monitor &
"$@"
